version: '3'

services:
  dnsmasq:
    image: marcovolpato00/dnsmasq-webproc:latest
    container_name: dnsmasq
    ports:
      - 5380:8080
      - '53:53/udp'
    environment:
      - HTTP_USER=admin
      - HTTP_PASS=dnsmasq
    # volumes:
    #   - SOME_PATH/dnsmasq.conf:/etc/dnsmasq.conf
    #   - SOME_PATH/lan.list:/etc/lan.list